name: Type Check

on:
    push:
        branches: []
    pull_request:
        branches: [ "main" ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: pip install mypy
      - run: mypy backend/src --ignore-missing-imports
